title: Feather CSS
description: A CSS framework that's light as a feather.
url: https://ryanwilke.github.io
permalink: /:title
sass:
  style: compressed

# Build settings
encoding: utf-8
markdown: kramdown

plugins:
  - jekyll-assets

assets:
  autowrite: true
  assets:
    - "*.svg"
  sources:
    - _assets/css
    - _assets/feather

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "docs"

# Exclude from processing.
exclude:
  - Gemfile*
