version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.15.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Dependency Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile
          working_directory: docs

      - save_cache:
          name: Cache Dependencies
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: yarn audit --level low
          working_directory: docs
      - run:
          command: yarn build
          working_directory: docs
      - run:
          command: yarn prettier:check
          working_directory: docs
      - run: yarn test:lint
      - run: yarn test:html
      - run: yarn test:vue
      - run: yarn test:unit:ci
      - run: yarn test:unit:coverage
