name: Production

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI Testing
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 11.x
      - uses: actions/cache@v1.0.1
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
      - run: npm install yarn -g
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn prettier:check
      - run: yarn test:lint
      - run: yarn test:vue
      - run: yarn test:html
      - run: yarn test:unit:ci
      - run: yarn test:unit:coverage
      - run: yarn git:init && yarn git:diff:template:compact
