name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to the NPM Registry
    runs-on: ubuntu-latest
    env:
      NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: 11.x
      - uses: actions/cache@v1.0.1
        id: cache
        with:
          path: dist
          key: package-${{ hashFiles('**/package.json') }}
      - run: npm install yarn -g
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn npm:publish
        if: steps.cache.outputs.cache-hit != 'true'
