name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to the NPM Registry
    runs-on: ubuntu-latest
    env:
      NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: 11.x
      - run: npm install yarn -g
      - run: yarn install
      - run: yarn npm:publish
