name: Test

on:
  pull_request:
    types: [opened, synchronize, labeled, ready_for_review]

jobs:
  ci:
    name: CI Tests
    runs-on: ubuntu-latest
    env:
      NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: 11.x
      - uses: actions/cache@v1.0.1
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
      - run: npm install yarn -g
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn build
      - run: yarn audit --level low
      - run: yarn install
        working_directory: docs
      - run: yarn build
        working_directory: docs
      - run: yarn prettier:check
        working_directory: docs
      - run: yarn test:lint
        working_directory: docs
      - run: yarn test:vue
        working_directory: docs
      - run: yarn test:html
        working_directory: docs
      - run: yarn test:unit:ci
        working_directory: docs
      - run: yarn test:unit:coverage
        working_directory: docs
      - run: yarn test:e2e:ci
        working_directory: docs
      - run: yarn test:e2e:percy
        working_directory: docs
        if: contains(github.event.pull_request.labels.*.name, 'Ready for Review')
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_BRANCH: ${{ github.head_ref }}
